
shows=([{'Title': 'The Sopranos', 'Genres': {'Drama', 'Crime'}, 'Rating': '9.2'},
        {'Title': 'The Wire', 'Genres': {'Drama', 'Crime', 'Thriller'}, 'Rating': '9.3'},
        {'Title': 'Breaking Bad', 'Genres': {'Drama', 'Crime', 'Thriller'}, 'Rating': '9.5'},
        {'Title': 'Mad Men', 'Genres': {'Drama'}, 'Rating': '8.7'},
        {'Title': 'Seinfeld', 'Genres': {'Comedy'}, 'Rating': '8.9'},
        {'Title': 'The Simpsons', 'Genres': {'Animation', 'Comedy'}, 'Rating': '8.7'},
        {'Title': 'The Twilight Zone', 'Genres': {'Drama', 'Fantasy', 'Horror'}, 'Rating': '9.1'},
        {'Title': 'Saturday Night Live', 'Genres': {'Comedy', 'Music'}, 'Rating': '8'},
        {'Title': 'All in the Family', 'Genres': {'Drama', 'Comedy'}, 'Rating': '8.4'},
        {'Title': 'The Daily Show', 'Genres': {'Comedy', 'News', 'Talk-Show'}, 'Rating': '8.3'},
        {'Title': 'Freaks and Geeks', 'Genres': {'Drama', 'Comedy'}, 'Rating': '8.8'},
        {'Title': 'Game of Thrones', 'Genres': {'Adventure', 'Drama', 'Action'}, 'Rating': '9.2'},
        {'Title': 'Late Show with David Letterman', 'Genres': {'Comedy', 'Talk-Show', 'Music'}, 'Rating': '7'},
        {'Title': 'The Larry Sanders Show', 'Genres': {'Comedy'}, 'Rating': '8.5'},
        {'Title': 'The West Wing', 'Genres': {'Drama'}, 'Rating': '8.9'},
        {'Title': 'M*A*S*H', 'Genres': {'Drama', 'Comedy', 'War'}, 'Rating': '8.4'},
        {'Title': 'Twin Peaks', 'Genres': {'Drama', 'Crime', 'Mystery'}, 'Rating': '8.8'},
        {'Title': 'Star Trek', 'Genres': {'Adventure', 'Action', 'Sci-Fi'}, 'Rating': '8.4'},
        {'Title': 'Curb Your Enthusiasm', 'Genres': {'Comedy'}, 'Rating': '8.8'},
        {'Title': 'Cheers', 'Genres': {'Drama', 'Comedy'}, 'Rating': '7.9'},
        {'Title': 'The Office', 'Genres': {'Drama', 'Comedy'}, 'Rating': '8.5'},
        {'Title': 'Louie', 'Genres': {'Drama', 'Comedy'}, 'Rating': '8.5'},
        {'Title': 'Deadwood', 'Genres': {'Drama', 'Crime', 'History'}, 'Rating': '8.6'},
        {'Title': 'Friday Night Lights', 'Genres': {'Drama', 'Sport'}, 'Rating': '8.7'},
        {'Title': 'Veep', 'Genres': {'Comedy'}, 'Rating': '8.4'},
        {'Title': 'Friends', 'Genres': {'Romance', 'Comedy'}, 'Rating': '8.9'},
        {'Title': 'Arrested Development', 'Genres': {'Comedy'}, 'Rating': '8.7'},
        {'Title': 'The X-Files', 'Genres': {'Drama', 'Crime', 'Mystery'}, 'Rating': '8.6'},
        {'Title': "Monty Python's Flying Circus", 'Genres': {'Comedy'}, 'Rating': '8.8'},
        {'Title': 'The Tonight Show Starring Johnny Carson', 'Genres': {'Comedy', 'Talk-Show'}, 'Rating': '8.5'},
        {'Title': 'Sesame Street', 'Genres': {'Adventure', 'Animation', 'Comedy'}, 'Rating': '8.1'},
        {'Title': 'I Love Lucy', 'Genres': {'Comedy', 'Family'}, 'Rating': '8.5'},
        {'Title': 'South Park', 'Genres': {'Animation', 'Comedy'}, 'Rating': '8.7'},
        {'Title': '30 Rock', 'Genres': {'Comedy'}, 'Rating': '8.3'},
        {'Title': 'My So-Called Life', 'Genres': {'Drama', 'Comedy', 'Romance'}, 'Rating': '8.4'},
        {'Title': 'Law & Order', 'Genres': {'Drama', 'Crime', 'Mystery'}, 'Rating': '7.8'},
        {'Title': 'Orange Is the New Black', 'Genres': {'Drama', 'Comedy', 'Crime'}, 'Rating': '8.1'},
        {'Title': 'Buffy the Vampire Slayer', 'Genres': {'Drama', 'Action', 'Fantasy'}, 'Rating': '8.3'},
        {'Title': 'Lost', 'Genres': {'Adventure', 'Drama', 'Fantasy'}, 'Rating': '8.3'},
        {'Title': 'The Shield', 'Genres': {'Drama', 'Crime', 'Thriller'}, 'Rating': '8.7'},
        {'Title': 'The Honeymooners', 'Genres': {'Comedy', 'Family'}, 'Rating': '8.6'},
        {'Title': 'NYPD Blue', 'Genres': {'Drama', 'Crime', 'Mystery'}, 'Rating': '7.7'},
        {'Title': 'The Americans', 'Genres': {'Drama', 'Crime', 'Mystery'}, 'Rating': '8.4'},
        {'Title': 'Columbo', 'Genres': {'Drama', 'Crime', 'Mystery'}, 'Rating': '8.3'},
        {'Title': 'Battlestar Galactica', 'Genres': {'Adventure', 'Drama', 'Action'}, 'Rating': '8.7'},
        {'Title': 'The Mary Tyler Moore Show', 'Genres': {'Comedy'}, 'Rating': '8.2'},
        {'Title': 'The Office', 'Genres': {'Comedy'}, 'Rating': '9'},
        {'Title': 'Taxi', 'Genres': {'Comedy'}, 'Rating': '7.7'},
        {'Title': 'ER', 'Genres': {'Drama', 'Romance'}, 'Rating': '7.9'},
        {'Title': 'Fargo', 'Genres': {'Drama', 'Crime', 'Thriller'}, 'Rating': '8.9'},
        {'Title': 'The Colbert Report', 'Genres': {'Comedy', 'News', 'Talk-Show'}, 'Rating': '8.4'},
        {'Title': 'The Bob Newhart Show', 'Genres': {'Comedy'}, 'Rating': '8.1'},
        {'Title': 'The Muppet Show', 'Genres': {'Comedy', 'Family', 'Music'}, 'Rating': '8.4'},
        {'Title': 'Six Feet Under', 'Genres': {'Drama', 'Comedy'}, 'Rating': '8.7'},
        {'Title': '24', 'Genres': {'Drama', 'Action', 'Crime'}, 'Rating': '8.4'},
        {'Title': 'Fawlty Towers', 'Genres': {'Comedy'}, 'Rating': '8.8'},
        {'Title': 'Hill Street Blues', 'Genres': {'Drama', 'Crime', 'Mystery'}, 'Rating': '8.2'},
        {'Title': 'Roots', 'Genres': {'Drama', 'Biography', 'History'}, 'Rating': '8.4'},
        {'Title': 'Beavis and Butt-Head', 'Genres': {'Animation', 'Comedy', 'Music'}, 'Rating': '7.5'},
        {'Title': 'Your Show of Shows', 'Genres': {'Comedy'}, 'Rating': '8.7'},
        {'Title': 'Sex and the City', 'Genres': {'Drama', 'Comedy', 'Romance'}, 'Rating': '7.3'},
        {'Title': 'The Wonder Years', 'Genres': {'Drama', 'Comedy', 'Family'}, 'Rating': '8.4'},
        {'Title': "Chappelle's Show", 'Genres': {'Comedy', 'Music'}, 'Rating': '8.8'},
        {'Title': 'Happy Days', 'Genres': {'Comedy', 'Family', 'Music'}, 'Rating': '7.4'},
        {'Title': 'Downton Abbey', 'Genres': {'Drama', 'Romance'}, 'Rating': '8.7'},
        {'Title': 'The Odd Couple', 'Genres': {'Comedy'}, 'Rating': '7.6'},
        {'Title': 'The State', 'Genres': {'Comedy'}, 'Rating': '8.5'},
        {'Title': 'The Ed Sullivan Show', 'Genres': {'Talk-Show', 'Music'}, 'Rating': '7.9'},
        {'Title': 'Roseanne', 'Genres': {'Drama', 'Comedy'}, 'Rating': '7'},
        {'Title': 'Mr. Show with Bob and David', 'Genres': {'Comedy'}, 'Rating': '8.4'},
        {'Title': 'Girls', 'Genres': {'Drama', 'Comedy'}, 'Rating': '7.4'},
        {'Title': 'Transparent', 'Genres': {'Drama', 'Comedy'}, 'Rating': '7.8'},
        {'Title': 'The Ren & Stimpy Show', 'Genres': {'Adventure', 'Animation', 'Comedy'}, 'Rating': '7.5'},
        {'Title': 'American Crime Story', 'Genres': {'Drama', 'Crime', 'Biography'}, 'Rating': '8.4'},
        {'Title': "Late Night with Conan O'Brien", 'Genres': {'Comedy', 'Talk-Show', 'Music'}, 'Rating': '8.2'},
        {'Title': 'The Walking Dead', 'Genres': {'Drama', 'Thriller', 'Horror'}, 'Rating': '8.1'},
        {'Title': 'Thirtysomething', 'Genres': {'Drama', 'Romance'}, 'Rating': '7.5'},
        {'Title': 'In Living Color', 'Genres': {'Comedy', 'Music'}, 'Rating': '8.1'},
        {'Title': 'The Fugitive', 'Genres': {'Adventure', 'Drama', 'Crime'}, 'Rating': '8.1'},
        {'Title': 'Dallas', 'Genres': {'Drama', 'Romance'}, 'Rating': '7'},
        {'Title': 'The Jeffersons', 'Genres': {'Comedy'}, 'Rating': '7.5'},
        {'Title': 'House of Cards', 'Genres': {'Drama'}, 'Rating': '8.7'},
        {'Title': 'Real Time with Bill Maher', 'Genres': {'Comedy', 'News', 'Talk-Show'}, 'Rating': '7.4'},
        {'Title': 'The Real World', 'Genres': {'Drama', 'Reality-TV'}, 'Rating': '5.1'},
        {'Title': 'Good Times', 'Genres': {'Comedy'}, 'Rating': '7.4'},
        {'Title': 'Doctor Who', 'Genres': {'Adventure', 'Drama', 'Sci-Fi'}, 'Rating': '8.6'},
        {'Title': 'Party Down', 'Genres': {'Drama', 'Comedy'}, 'Rating': '8.2'},
        {'Title': 'Homeland', 'Genres': {'Drama', 'Crime', 'Mystery'}, 'Rating': '8.3'},
        {'Title': 'The Dick Van Dyke Show', 'Genres': {'Comedy', 'Family'}, 'Rating': '8.4'},
        {'Title': 'Broad City', 'Genres': {'Comedy'}, 'Rating': '8.4'},
        {'Title': 'American Idol', 'Genres': {'Game-Show', 'Reality-TV', 'Music'}, 'Rating': '4.2'},
        {'Title': 'Mystery Science Theater 3000', 'Genres': {'Comedy', 'Sci-Fi'}, 'Rating': '8.7'},
        {'Title': 'Jeopardy!', 'Genres': {'Game-Show'}, 'Rating': '8.3'},
        {'Title': 'Key and Peele', 'Genres': {'Adventure', 'Action', 'Comedy'}, 'Rating': '8.3'},
        {'Title': 'Gunsmoke', 'Genres': {'Western'}, 'Rating': '8.1'},
        {'Title': 'Portlandia', 'Genres': {'Comedy'}, 'Rating': '7.8'},
        {'Title': 'The Golden Girls', 'Genres': {'Drama', 'Comedy'}, 'Rating': '8.1'},
        {'Title': 'Oz', 'Genres': {'Drama', 'Crime', 'Thriller'}, 'Rating': '8.7'},
        {'Title': 'Eastbound & Down', 'Genres': {'Drama', 'Comedy', 'Sport'}, 'Rating': '8.3'}])
       
